export const FETCH_USER_DATA = 'FETCH_USER_DATA';
export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE';
export const FETCH_CARDS = 'FETCH_CARDS';
export const FETCH_TRANSACTIONS = 'FETCH_TRANSACTIONS';
export const FETCH_CHART_DATA = 'FETCH_CHART_DATA';