enum DashboardActionTypes {
  SET_CARDS_DATA = "SET_CARDS_DATA",
  SET_CARDS_DATA_API_STATUS = "SET_CARDS_DATA_API_STATUS",
  SET_RECENT_TRANSACTIONS = "SET_RECENT_TRANSACTIONS",
  SET_RECENT_TRANSACTIONS_API_STATUS = "SET_RECENT_TRANSACTIONS_API_STATUS",
  SET_WEEKLY_ACTIVITY = "SET_WEEKLY_ACTIVITY",
  SET_WEEKLY_ACTIVITY_API_STATUS = "SET_WEEKLY_ACTIVITY_API_STATUS",
  SET_EXPENSES = "SET_EXPENSES",
  SET_EXPENSES_API_STATUS = "SET_EXPENSES_API_STATUS",
}

export default DashboardActionTypes;
